version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "url_shortener_container"
    restart: on-failure
    environment:
      - HTTP-IP=0.0.0.0
      - HTTP-PORT=30001
      - REDIS_HOST=db
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    tty: true
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "30001:30001"
  db:
    image: redis
    restart: always
    container_name: "redis_db_container"
    ports:
      - "6379:6379/tcp"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  data:
networks:
  app_network:
    driver: bridge